#Configuração da database de desenvolvimento  
development:
   adapter: postgresql
   encoding: unicode
   database: fisioup_development
   host: localhost
   pool: 5
   username: ubuntu
   password: fsp-up

#Configuração da database de teste
test: 
   adapter: postgresql
   encoding: unicode
   database: fisioup_test
   host: localhost
   pool: 5
   username: ubuntu
   password: fsp-up
 
#Configuração da database de produção 
production: 
   adapter: postgresql
   encoding: unicode
   database: fisioup_production
   host: localhost
   pool: 5
   username: ubuntu
   password: fsp-up